### ISSUE TITLE
asset ticker lenght: consistency between regex and error message

### ISSUE THREAD

**Issue by St333p** [LNP-BP/rgb-node#101]
The following function validates the asset ticker format (in `src/api/fungible.rs`):
```rust
fn ticker_validator(name: &str) -> Result<(), String> {
    let re = Regex::new(r"^[A-Z]{3,8}$").expect("Regex parse failure");
    if !re.is_match(&name) {
        Err(
            "Ticker name must be between 2 and 8 chars, contain no spaces and \
            consist only of capital letters\
            "
            .to_string(),
        )
[...]
```
Which is the correct minimum asset ticker length, 2 or 3?

**Comment by dr-orlovsky** [comment]
While we do not have a lower bound for the number of characters at the Schema level (https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0020.md) and it can't be enforced there I think we need UI to prevent from creating tickers with less than tree characters here.

**Comment by dr-orlovsky** [comment]
+ filed an issue/open question for the next call: https://github.com/LNP-BP/rust-lnpbp/issues/148

**Comment by St333p** [comment]
So I'll wait till the next call, just to see the opinion of others. Then I'll probably just fix the error message if we want to limit it to 3-8 chars, totally makes sense to me.

**Comment by dr-orlovsky** [comment]
Moving this to the next release since enforcing lower limit will require deep changes in LNP/BP Core library. 

Fixed inconsistency in error message and regex for now and will leave this restrictuon to be UI-enforced only (on the CLI level)
