### ISSUE TITLE
A similar path exists: `electrum_client::serde`

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/rgb-node#107]
I get an error while trying to install rgb-node by using the local install instructions and even when taking 
![image](https://user-images.githubusercontent.com/176074/99935546-38071d00-2d61-11eb-9beb-c78ebfe0f927.png)
the docker path:
sudo apt update
sudo apt install -y build-essential pkg-config libzmq3-dev libssl-dev libpq-dev cmake
git clone https://github.com/LNP-BP/rgb-node.git
cd rgb-node
cargo build --release

I got the error:

error[E0432]: unresolved import `serde`
  --> src/api/fungible.rs:15:5
   |
15 | use serde::{Deserialize, Serialize};
   |     ^^^^^ help: a similar path exists: `electrum_client::serde`

error[E0432]: unresolved import `serde`
  --> src/util/seal_spec.rs:16:5

Trying Docker

![image](https://user-images.githubusercontent.com/176074/99935183-63d5d300-2d60-11eb-9e6f-db344a7990f1.png)

**Comment by rajarshimaitra** [comment]
Thanks @Goosie for the report. Great catch!! It was missed by the CI tests.

Fixed the bug. 

Opening the PR in a moment.

**Comment by rajarshimaitra** [comment]
It should work after the above merge.

**Comment by rajarshimaitra** [comment]
Hi @Goosie , it seems a proper fix will take a little longer. In the meantime you can simply put "serde" inside `client` feature in `Cargo.toml`. It's a single word change. Please refer to my PR above. That should fix the bug and you can continue from there. 

A more comprehensive fix will be done soon.

**Comment by Goosie** [comment]
Thanks the compiling is working now.

**Comment by dr-orlovsky** [comment]
With 0.2 beta 4 release the issue is fixed (https://github.com/LNP-BP/rgb-node/releases/tag/v0.2.0-beta.4)
