### ISSUE TITLE
Build issues of lnpbp/master for rgb-node

### ISSUE THREAD

**Issue by rajarshimaitra** [LNP-BP/rgb-node#111]
While building rgb-node with lnpbp master branch, the following cargo error is occuring.

Cargo.toml:
```
lnpbp = { git = "https://github.com/LNP-BP/rust-lnpbp", branch = "master", features = ["lnp", "url", "websockets"] }
```

cargo error:
```
error: failed to select a version for `cmake`.
    ... required by package `zeromq-src v0.1.10+4.3.2`
    ... which is depended on by `zmq-sys v0.11.0`
    ... which is depended on by `zmq v0.9.2`
    ... which is depended on by `lnpbp v0.2.0-beta.2`
    ... which is depended on by `lnpbp_services v0.2.0-beta.2`
    ... which is depended on by `rgb_node v0.2.0-beta.3 (/home/raj/github-repo/rgb-node)`
versions that meet the requirements `=0.1.44` are: 0.1.44

all possible versions conflict with previously selected packages.

  previously selected package `cmake v0.1.43`
    ... which is depended on by `zeromq-src v0.1.10+4.3.2 (https://github.com/LNP-BP/zeromq-src-rs?branch=fix/cmake#e95a4e68)`
    ... which is depended on by `lnpbp v0.2.0-beta.3 (https://github.com/LNP-BP/rust-lnpbp?branch=master#4d064975)`
    ... which is depended on by `rgb_node v0.2.0-beta.3 (/home/raj/github-repo/rgb-node)`

failed to select a version for `cmake` which could resolve this conflict
```

Not sure what's happening here, seems like `cmake` requires different versions for different crates?

**Comment by rajarshimaitra** [comment]
cc: @dr-orlovsky 

@dieeasy  Have you seen something similar or any input you can provide on this?

**Comment by rajarshimaitra** [comment]
Notes after further investigation:

- This particular version issue goes away with `cargo update` and `rm -rf target`. 

- But it's not ideal to try to build `lnpbp-master` here because this will create a conflicting compilation of both versions, `master` and `v0.2-beta.2`. Because `lnpbp-derive` and `lnpbp-service` depends on `v0.2-beta.2`. 

To put it in context I require `lnpbp-master` to use https://github.com/LNP-BP/rust-lnpbp/pull/153 while implementing hammerbald. 

What would be the right way to this? Or in general in such a situation where some added logic is required which is not available in the latest release tag?

**Comment by rajarshimaitra** [comment]
Removing `Bug` because this is not a functional failure.

**Comment by dr-orlovsky** [comment]
With 0.2 beta 4 released pls check whether the issue got fixed (it should be now)

**Comment by dr-orlovsky** [comment]
My checks show that the issue is solved with RC2
