### ISSUE TITLE
Expose `import_asset`, `export_asset` and `list_assets` methods

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/rgb-node#117]
let's add to the `i9n` module the methods:
- `import_asset`, calling the method in `src/contracts/fungible/runtime.rs`
- ~~`invoice`, defined as here https://github.com/LNP-BP/rgb-node/blob/master/src/cli/fungible.rs#L412-L429~~ (https://github.com/LNP-BP/rgb-sdk/issues/28#issuecomment-739570302)
- `list_assets` (https://github.com/LNP-BP/rgb-sdk/issues/28#issuecomment-739324980)
- `export_asset`

@dr-orlovsky please correct me if I'm wrong

**Comment by dr-orlovsky** [comment]
That's right, and `list` method as well

**Comment by dr-orlovsky** [comment]
Seems like this issue is a blocking and a priority for v0.2 release

**Comment by zoedberg** [comment]
Currently working on LNP-BP/rgb-sdk#24 and LNP-BP/rgb-sdk#29, but I can temporarily pause those to do this.
Actually I've already started working on this some days ago, then encountered some obstacles (while updating the `issue` call params on the sdk, task required to switch to latest rgb-node release) and so I paused the job. If you want to do this task, I can push my intermediate results so you already have something to start from

**Comment by dr-orlovsky** [comment]
I can do the stuff quick, but I thought you are interested in trying to play with the Node code, not just SDK around it, and this may be a good first issue. Your WIP PR will be in any way useful

**Comment by zoedberg** [comment]
I am interested, but currently a bit overloaded by tasks. I will give it another try tomorrow, and if not succeed quickly, I'll open a draft PR

**Comment by dr-orlovsky** [comment]
Yeah, feel free to postpone other tasks, they are not that critical to do the release
