### ISSUE TITLE
Add macOS dependencies to README

### ISSUE THREAD

**Issue by jharveyb** [LNP-BP/rgb-node#121]
rgb-node builds & runs without issue on macOS, but the dependencies do have different names from Ubuntu / Debian-based distros.

Specifically, using [Brew](https://brew.sh), the relevant command would be:

`brew install cmake libpq sqlite pkg-config openssl zmq`

**Comment by UkolovaOlga** [comment]
Thanks for pointing that out!
Can I please ask you to create a PR with the corresponding changes and assign that to me for a review? Or mention me in the description. Thanks!
