### ISSUE TITLE
RGB CLI Issue: FrameTooSmall

### ISSUE THREAD

**Issue by bigdhri** [LNP-BP/rgb-node#124]
Hi,
   I have just recently downloaded your latest tags, v0.2.1, and seem to be encountering an issue when trying to execute the CLI...Rust version: 1.48.0
Command used to build RGB:
cargo build --release --all-features
Command used to start RGB:
./target/release/rgbd --data-dir ./data --bin-dir target/release -vvvv --contract fungible
CLI Command:
rgb-cli command issued:
rgb-cli -d ./data -vvvv fungible list
Error Encountered:
2020-12-21T17:30:01Z ERROR rgb::contracts::fungible::runtime] Error processing API request: Lnp(FrameTooSmall(2))
Any help would be appreciated...
Thanks!

**Comment by bigdhri** [comment]
Hi,
    I have tried rebuilding and doing a few other things but still no luck. I did however realize that when I try to start the rgbd I get this error at the top:
./target/debug/rgbd -vv --data-dir ./data --bin-dir ./target/debug/ --contract fungible
thread 'main' panicked at 'internal error: entered unreachable code', src/rgbd/runtime.rs:210:9
Has anyone seen/encountered this before?
Thanks,
Dave

**Comment by UkolovaOlga** [comment]
what Rust version are you using? you need to use Rust nightly version (please check if that's the case)

**Comment by bigdhri** [comment]
@UkolovaOlga Thank you for the suggestion, I will give it a try and let you know how I make out. My current rust versions are:
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: checking for self-updates

   stable-x86_64-apple-darwin unchanged - rustc 1.48.0 (7eac88abb 2020-11-16)
  nightly-x86_64-apple-darwin unchanged - rustc 1.51.0-nightly (158f8d034 2020-12-29)

**Comment by dr-orlovsky** [comment]
>  rgb-cli -d ./data -vvvv fungible list

From what I read, it may be that the system fails to return an empty list of assets. Can you try some other command, for instance a command issuing an asset?

**Comment by bigdhri** [comment]
Thanks @dr-orlovsky, I tried still an issue possibly...
Command: rgb-cli -d ./data -vvvv fungible issue "DHTKN" "Test DH Token" 100@66200d1b6f4d9dcb550dac03a08824bdfc9600df940cc12a35287a493c45d2ff:0
Error Returned:
2020-12-30T20:44:31Z DEBUG rgb::stash::runtime] Got ADD_SCHEMA schema1qxx4qkcjsgcqehyk7gg9lrp8uqw9a34r8r0qfay0lmcr3pxh7yrr2n2mvszq0s7symvkvdcf2ck6whm9zpgpqyk2nqypf8pget8vlk798ccuats4jzzn98ena4p2us7eyvmxvsz5zzvcc4yu5nvjdhlw76rkxn8vvs27f0qs4qyemfdfczyvve45qvfds8kryuuc4kzh03t2xruw932u6e7rn9szn8uz2kkcc7lrkzpw4ct4xpgej2s8e3vn224mmwh8yjwm3c3uzcsz350urqt6gfm6wpj6gcajd6uevncqy74u87jtfmx8raza9nlm2hazydl7hyevmls6amyy4kl7rv6skggq
[2020-12-30T20:44:31Z DEBUG rgb::stash::runtime] API request processing complete
[2020-12-30T20:45:48Z ERROR rgb::contracts::fungible::runtime] Error processing API request: Lnp(InvalidLength)
[2020-12-30T20:45:48Z DEBUG zmq] socket dropped
[2020-12-30T20:45:48Z DEBUG zmq] socket dropped
[2020-12-30T20:45:48Z DEBUG zmq] socket dropped
[2020-12-30T20:45:48Z DEBUG zmq] socket dropped
thread 'main' panicked at 'Fungible contract runtime run loop has failed with error Lnp(InvalidLength)', /Users/davidhill/rgb-node/src/service.rs:39:9
stack backtrace:
   0: std::panicking::begin_panic
   1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: std::thread::local::LocalKey<T>::with
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on
   7: fungibled::main

**Comment by dr-orlovsky** [comment]
This is indeed very strange. Usually such bugs means that client and daemon runs different protocol versions.

Can you try
```
git reset --hard v0.2.1
rm -rf target
cargo build --all-targets --all-features
```

and try once again both commands?

**Comment by bigdhri** [comment]
@dr-orlovsky 
Thank you for the help, I tried what you recommended with no luck sadly. But I did remove rust and reinstall rust from scratch and that seemed to fix the issue now. I can make all rgb-cli calls successfully now. I am not sure how my rust instance went bad, but it is all set now. Thank you again for the suggestions.
Dave

**Comment by dr-orlovsky** [comment]
It's really weird, never heard about something like that - that rust re-install solves issue in a compiled rust program...
