### ISSUE TITLE
Bounty: compile the zmq library for iOS

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/rgb-node#14]
## Description
Compile the [zmq library](https://zeromq.org/) with any of iOS versions from 10.3.3 till 13.6

### Expected result:
the library compiles and it is possible to call its methods from the app.

**Comment by dr-orlovsky** [comment]
The problem was solved by running `make clean`

**Comment by mileschet** [comment]
@dr-orlovsky, there was some bugs on build_ios.sh, here it is [updated](https://github.com/mileschet/libzmq/blob/ios135/builds/ios/build_ios.sh) version. thank you!

**Comment by dr-orlovsky** [comment]
Bounty was successfully solved by @mileschet with https://github.com/zeromq/libzmq/commit/571045d1295b0db27e58c2e2ead7e5e9599a5aa5 !
