### ISSUE TITLE
Build error due to compiler upgrade

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/rgb-node#28]
I get the following error after installation steps on ubuntu 18.04. Mentioned:

mismatched types
  --> /home/alice/.cargo/git/checkouts/rust-lnpbp-1c6b6ac6d4fb658b/dbd0d32/src/rgb/contract/amount.rs:92:48
   |
92 |         match (&self.commitment.0).partial_cmp(&other.commitment.0[..]) {
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^ expected array `[u8; 33]`, found slice `[u8]`
   |
   = note: expected reference `&[u8; 33]`
              found reference `&[u8]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `lnpbp`.

swig -version: 4.02
python --version: 2.7.17

rustc --explain E0308 gives:

Expected type did not match the received type.

Erroneous code example:

```
let x: i32 = "I am not a number!";
//     ~~~   ~~~~~~~~~~~~~~~~~~~~
//      |             |
//      |    initializing expression;
//      |    compiler infers type `&str`
//      |
//    type `i32` assigned to variable `x`
```

This error occurs when the compiler is unable to infer the concrete type of a
variable. It can occur in several cases, the most common being a mismatch
between two types: the type the author explicitly assigned, and the type the
compiler inferred.
![mismatched types](https://user-images.githubusercontent.com/176074/88523903-fa83c480-cff8-11ea-8f0f-7cbabae48111.png)

**Comment by rajarshimaitra** [comment]
I am not sure why this would happen. Build passed cleanly in my local. Check if you are on master or reclone the repo.

**Comment by dr-orlovsky** [comment]
Hi! Thanks for reporting. Pls see https://github.com/LNP-BP/rust-lnpbp/pull/57#issuecomment-665042131
