### ISSUE TITLE
Build fails after seal blinding upgrade to 64 bit

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-node#29]
We have an RGB node build failing after LNP/BP Core library adopting 64-bit blinding factors for seal definitions after https://github.com/LNP-BP/rust-lnpbp/pull/52 acceptance

**Comment by Goosie** [comment]
Let me know when I can help with testing or whatever.

**Comment by rajarshimaitra** [comment]
RGB build succeeds after deleting `Cargo.lock` and `target` in my local at master#[9f0e839](https://github.com/LNP-BP/rust-lnpbp/commit/9f0e8399f6fa6fcbc5c8d23d6d42eecc51144cfd)
```
   Compiling lnpbp v0.1.0-beta.3 (https://github.com/lnp-bp/rust-lnpbp?branch=master#9f0e8399)
   Compiling rgb_node v0.1.0-beta.2 (/home/raj/github-repo/rgb-node)
warning: use of deprecated item 'std::vec::Vec::<T>::remove_item': Removing the first item equal to a needle is already easily possible with iterators and the current Vec methods. Furthermore, having a method for one particular case of removal (linear search, only the first item, no swap remove) but not for others is inconsistent. This method will be removed soon.
   --> src/contracts/fungible/data/asset.rs:171:21
    |
171 |         allocations.remove_item(&old_allocation).is_some()
    |                     ^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 2m 34s
```

@Goosie is the issue still persisting at your end?

**Comment by rajarshimaitra** [comment]
Hi @Goosie thanks for the report. Posted a fix in rust-lnpbp https://github.com/LNP-BP/rust-lnpbp/pull/58.

You can try changing the lnp-bp dependency to my branch https://github.com/rajarshimaitra/rust-lnpbp/tree/build-fix-28/07 
And see if the build passes. Hopefully, this should do the fix.

**Comment by Goosie** [comment]
Yess thanks, No errors after cargo build --release now. Thanks!, Up to the next steps :-)

**Comment by Goosie** [comment]
I react to early. I removed the rgb-node directory. Cloned the repository from rgb-node again and changed the path in Cargo.toml Under section [dependencies.lnpbo] I changed the path
git = "https://github.com/lnp-bp/rust-lnpbp" into git = "https://github.com/rajarshimaitra/rust-lnpbp" After running  cargo build --release I get the same error as started:
error[E0308]: mismatched types
  --> /home/alice/.cargo/git/checkouts/rust-lnpbp-a0ee553585762f76/2f6fee7/src/rgb/contract/amount.rs:92:48
   |
92 |         match (&self.commitment.0).partial_cmp(&other.commitment.0[..]) {
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^ expected array `[u8; 33]`, found slice `[u8]`
   |
   = note: expected reference `&[u8; 33]`
              found reference `&[u8]`

Do I have to change the path somewhere else maybe?

**Comment by rajarshimaitra** [comment]
>git = "https://github.com/lnp-bp/rust-lnpbp" into git = "https://github.com/rajarshimaitra/rust-lnpbp" After running cargo build --release I get the same error as started:

Right, just one more change. Add the branch name too like this in `Cargo.toml`
```
[dependencies.lnpbp]
git = "https://github.com/rajarshimaitra/rust-lnpbp"
branch = "build-fix-28/07"
features = ["all"]
```

**Comment by Goosie** [comment]
Yess. It's working now :-)

**Comment by dr-orlovsky** [comment]
I actually did a fix in a master commit two days before, but it appears that I have not added the required changes to it with `git add` :) So I have merged @rajarshimaitra PR now and you can link to the master

**Comment by dr-orlovsky** [comment]
@rajarshimaitra can you pls work on fixing the issue with u32->u64 here in RGB node after LNP/BP change? The discussion here is actually misleading, since it's about an unrelated issue (namely fixed with some other your PR)...

**Comment by rajarshimaitra** [comment]
Yes working on it.
