### ISSUE TITLE
handle library updates

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/rgb-node#54]
As partially discussed in #35, we need to properly handle library updates.

Currently the `Cargo.lock` file is not committed (it's git-ignored), meaning that shared "reproducible" builds are not possible.
As described [here](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) committing the lock file is important when the library has to be built directly by a user (as in the case of building the android bindings).

The only drawback I see in doing this is that the project developers will have to commit eventual updates of the file.

As an alternative, we should document that running `cargo update` may be necessary when re-building an updated version of this library.

The drawback here is that a user could still incur in issues when re-building the library and then have to check the documentation looking for a solution.

**Comment by rajarshimaitra** [comment]
Seems like a good idea to me to check `Cargo.lock` in git. 
>The only drawback I see in doing this is that the project developers will have to commit eventual updates of the file.

Can you elaborate on this a little? Will the lock file update every time devs build and push in master? What can be the major problem in workflow that devs need to keep in mind because of this?

**Comment by dr-orlovsky** [comment]
Ok, let's try commit Cargo.lock; I will do this

**Comment by dr-orlovsky** [comment]
Closed with https://github.com/LNP-BP/rust-lnpbp/commit/411e307886b919943b9acf389e209c28aa837be6

**Comment by zoedberg** [comment]
> Seems like a good idea to me to check `Cargo.lock` in git.
> 
> > The only drawback I see in doing this is that the project developers will have to commit eventual updates of the file.
> 
> Can you elaborate on this a little? Will the lock file update every time devs build and push in master? What can be the major problem in workflow that devs need to keep in mind because of this?

The lock file will update each time one runs `cargo update`. Each time it changes, the developer that is updating should check that the sw still works correctly with the new dependencies. This could mean just running tests (if they have a good coverage) or manually testing the sw (to stimulate function calls from those updated libraries). If any problem arises an issue should be opened to fix library upgrades.

A little more maintenance in exchange for consistency across developers

**Comment by dr-orlovsky** [comment]
Can you add this info to README please?
