### ISSUE TITLE
SQLite storage engine for cached data

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-node#58]
We need to impl `Cache` from https://github.com/LNP-BP/rgb-node/blob/master/src/contracts/fungible/cache/cache.rs for a new type working with SQLite backend, like it is did for file-backed backend in https://github.com/LNP-BP/rgb-node/blob/master/src/contracts/fungible/cache/file.rs

Best to use Diesel crate, like it is used in BP Node

**Comment by rajarshimaitra** [comment]
Working on this.
