### ISSUE TITLE
Clean install error: Rust E0554

### ISSUE THREAD

**Issue by unconst** [LNP-BP/rgb-node#86]
DESCRIPTION:
Installed from a clean cargo/rust installation on MacOS Catalina.  Throws rust E0554 requiring that I run with the nightly cargo installed. 

COMMAND:
>> cargo install --path .         

ERROR:
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/const/.cargo/git/checkouts/rust-lnpbp-1c6b6ac6d4fb658b/d430af6/derive/src/lib.rs:17:1
  |
17 | #![feature(try_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^

FULL LOGS:              
>> cargo install --path .       
  Installing rgb_node v0.1.0-rc.1 (/Users/const/Workspace/RGB/rgb-node)
    Updating git repository `https://github.com/LNP-BP/rust-bitcoin`
    Updating git repository `https://github.com/LNP-BP/bitcoin_hashes`
    Updating git repository `https://github.com/LNP-BP/rust-miniscript`
    Updating git repository `https://github.com/LNP-BP/zeromq-src-rs`
    Updating crates.io index
    Updating git repository `https://github.com/LNP-BP/rust-lnpbp`
   Compiling lnpbp_derive v0.1.0-rc.1 (https://github.com/LNP-BP/rust-lnpbp#d430af61)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/const/.cargo/git/checkouts/rust-lnpbp-1c6b6ac6d4fb658b/d430af6/derive/src/lib.rs:17:1
   |
17 | #![feature(try_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: failed to compile `rgb_node v0.1.0-rc.1 (/Users/const/Workspace/RGB/rgb-node)`, intermediate artifacts can be found at `/Users/const/Workspace/RGB/rgb-node/target`

Caused by:
  could not compile `lnpbp_derive`.

To learn more, run the command again with --verbose.

**Comment by dr-orlovsky** [comment]
As said in instructions you need to use nigtly rust toolchain
