### ISSUE TITLE
Improving integration (i9n) module

### ISSUE THREAD

**Issue by jharveyb** [LNP-BP/rgb-node#92]
Hi,

I have seen the rgb-sdk, which looks useful for using rgb-node from another language. However, I would like to integrate in a Rust project. I have a working solution, but it seems like perhaps there is a more straighforward way to start and talk to rgbd.

Specifically, to start rgbd I mimic the approach used [here](https://github.com/LNP-BP/rgb-node/blob/master/src/i9n/runtime.rs#L32), which works well since my program is not async at the moment.

To issue commands, I am mimicking the rgb-cli binary, but it is a bit awkward. Instead of parsing any input, I build [commands](https://github.com/LNP-BP/rgb-node/blob/master/src/cli/fungible.rs#L38) manually. Building an Opts struct manually seems unworkable, since the config module is not puclic, so the  [Command](https://github.com/LNP-BP/rgb-node/blob/master/src/cli/config.rs#L60) enum there cannot be used.

Given the command and CLI config, RPC calls work - I am just wondering if I can make calls to rgbd without going through the CLI module, or if there is some other more idiomatic way to mimic the CLI demo from a Rust program.

**Comment by dr-orlovsky** [comment]
Hi,

To integrate with RGB Node, first you have to decide do you need the node be embedded into your software (running in separate threads, not processes alongside) or it will use a separate standalone node hosted on desktop, personal or enterprise server. In case you need the later, you do not need to initialize node at all. This part is the same for both integrating from rust and from outside.

Now, to use RGB Node from Rust in both of the cases you do not have to replicate `cli`, but just simply use functions exposed in `i9n` mod. All interaction with RGB Node is done through ZeroMQ RPC API, and `i9n` just abstracts construction of RPC requests with convenient functions like `i9n::Runtime::transfer(...)`. To use them you only have to instantiate integration runtime by doing `let runtime = i9n::Runtime::init()` passing it a config object, specifying how to connect to the RGB Node.

Pls let me know if you need further guidance or the explanation is clear.

**Comment by jharveyb** [comment]
Hi,

This explanation makes sense. 

I think I would likely run it as separate threads, as a child of the main wallet process.

Using the functions from i9n makes sense, but for my use case I would want to access other calls such as import/export, listing assets, and accepting assets.It seems a problem with interfacing through `cli` is responses going to stdout instead of the returned values for calls.

**Comment by dr-orlovsky** [comment]
You can't interact with the node though `cli`; it is for command line tool only. If any functions is absent from `i9n` we will just add them (or feel free to do a PR)

**Comment by jharveyb** [comment]
Hmm, I am currently using a cli Runtime object to interact with rgb-node. But I agree, going through the i9n module is a more correct way to do this.

Outside of listing assets, importing and exporting assets would be useful, as well as accepting and validating assets.

I'm not sure how much can be done now by just reading files - I will likely try to implement some of these myself and submit a PR later.

**Comment by dr-orlovsky** [comment]
For accepting and validation you need a function in `i9n` which, as I see, is not there. So yes, we need to add it (and can use cli as an example). Would you like to try doing that?

Not sure what do you mean by "exporting asset" or "importing". In cli you export only list of assets or information about its allocation, which is found in the file I pointed previously. And there is no way to "import" anything without doing an actual asset transfer.

**Comment by jharveyb** [comment]
Yes, I can try and implement support for accepting.

I understand now your point about an import being a transfer - I think these may have been older commands related to genesis hashes, not the actual assets.

Looking forward to the work being done in #91

**Comment by dr-orlovsky** [comment]
Oh yes, you probably mean schema and genesis import. This can be done as a functions in `i9n` for sure!

#91 is merged

**Comment by dr-orlovsky** [comment]
@jharveyb, genesis import is implemented with https://github.com/LNP-BP/rgb-node/pull/120/files#diff-4f1e719fc4596f679ca2c353596a44931590a5ffc74e1c115321f741298ff2e0R221-R230

We will not have schema import for now since we support only a single schema, RGB20

**Comment by dr-orlovsky** [comment]
Finally fixed: this was the issue source

https://github.com/LNP-BP/rgb-node/commit/2e549cd3491db2e412a5f0543d9495b750d2d3ae#diff-4f1e719fc4596f679ca2c353596a44931590a5ffc74e1c115321f741298ff2e0R109-R111

The fixed version is published as `rgb-node` v0.2.1 crate
