### ISSUE TITLE
Expose `validate` and `accept` methods

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-node#97]
These two methods https://github.com/LNP-BP/rgb-node/blob/4740b4c2aaf354fb5d3effb7403510e33cefc687/src/contracts/fungible/runtime.rs#L415-L432 should be exposed in `i9n` mod here https://github.com/LNP-BP/rgb-node/blob/4740b4c2aaf354fb5d3effb7403510e33cefc687/src/i9n/fungible.rs#L156

By "expose" I mean make a method in `i9n` that calls to `fungible` via ZMQ RPC API as it does for `transfer`

@zoedberg @rajarshimaitra pls let me know if any of you would like to pick this task

**Comment by zoedberg** [comment]
I can try to do this, I'll let you know if I face any difficulty
